name: pore
channels:
  - conda-forge
  - bioconda
dependencies:
  - fastqc
  - porechop
  - nanopolish
  - minimap2
  - miniasm
  - racon
  - graphmap
  - bwa
  - samtools
  - picard
  - nanostat
  - nanoplot
