name: pore
channels:
  - conda-forge
  - bioconda
dependencies:
  - assembly-stats
  - bcftools
  - biopython
  - bwa
  - fastqc
  - graphmap
  - ipywidgets
  - iqtree
  - mafft
  - minimap2
  - miniasm
  - mosdepth
  - nanoplot
  - nanopolish
  - nanostat
  - notebook
  - numpy
  - matplotlib
  - pandas
  - papermill
  - picard
  - pip
  - porechop
  - racon
  - samtools
  - seqkit
  - setuptools
  - snakemake
  - pip:
    - kindel
    - medaka
    - qcat



