#!/bin/bash

# Install a JupyterLab extension
jupyter labextension install @ijmbarr/jupyterlab_spellchecker
jupyter labextension install @jupyterlab/toc

# enable nbextensions and its configurator
jupyter contrib nbextension install --user
jupyter nbextensions_configurator enable --user
jupyter nbextension enable widgetsnbextension
jupyter nbextension enable toc2/main
jupyter nbextension enable freeze/main
jupyter nbextension enable table_beautifier/main
jupyter nbextension enable varInspector/main

